epochs: 300000
batch_size: 400
data_config: configs/datasets/non_cyclical_clustered_hsv.yaml
checkpoint_dir: /storage/checkpoints
experiment_name: Clustered_HSV_CCStarGAN
train_config: "configs/training.yaml"
model: models.ccgan.CCStarGAN
model_hyperparams: configs/models/stargan.yaml
n_nodes: 1
n_gpus: 2
n_workers: 5
node_rank: 0
embed_generator: True
embed_discriminator: false
ccgan_embedding_file: /storage/embeddings/clustered_hsv/embedding.pt
ccgan_embedding_dim: 128
discriminator_lr: 0.0002
generator_lr: 0.0002
optimizer: adam
