epochs: 1000
batch_size: 1024
data_config: configs/datasets/clean_continuous_hsv.yaml
checkpoint_dir: /storage/checkpoints
experiment_name: HSV
train_config: "configs/training.yaml"
model: models.ccgan.CCFPGAN
model_hyperparams: configs/models/fpgan.yaml
n_nodes: 1
n_gpus: 4
n_workers: 20
node_rank: 0
ccgan: True
ccgan_vicinity_type: soft
ccgan_embedding_file: /storage/embeddings/cyclical_clean_continuous_hsv/embedding.pt
ccgan_embedding_dim: 128
embed_discriminator: False
cyclical: True
