epochs: 1000
batch_size: 1024
data_config: configs/datasets/hue_f_mnist.yaml
checkpoint_dir: checkpoints
experiment_name: HSV_CCFPGAN
train_config: "configs/training.yaml"
model: models.ccgan.CCFPGAN
model_hyperparams: configs/models/fpgan.yaml
n_nodes: 1
n_gpus: 4
n_workers: 20
node_rank: 0
ccgan: True
ccgan_vicinity_type: hard
ccgan_embedding_file: /storage/checkpoints/embeddings/hsv_fmnist/embedding.pt
ccgan_embedding_dim: 128
embed_discriminator: True
