epochs: 300
batch_size: 1024
data_config: configs/datasets/hue_f_mnist.yaml
checkpoint_dir: /storage/checkpoints
experiment_name: HSV_FPGAN
train_config: "configs/training.yaml"
model: models.fpgan.FPGAN
model_hyperparams: configs/models/fpgan.yaml
n_nodes: 1
n_gpus: 4
node_rank: 0
ccgan: False
