epochs: 300000
batch_size: 500
data_config: configs/datasets/non_cyclical_hsv.yaml
checkpoint_dir: /storage/checkpoints
experiment_name: HSV_CCFPGAN
train_config: "configs/training.yaml"
model: models.ccgan.CCFPGAN
model_hyperparams: configs/models/fpgan.yaml
n_nodes: 1
n_gpus: 2
n_workers: 5
node_rank: 0
embed_generator: True
ccgan_embedding_file: /storage/embeddings/non_cyclical_hsv/embedding.pt
ccgan_embedding_dim: 128
embed_discriminator: True
