epochs: 300000
data_config: configs/datasets/quickdraw.yaml
experiment_name: QuickDraw
train_config: "configs/training.yaml"
model: models.ccgan.CCStarGAN
model_hyperparams: configs/models/stargan.yaml
n_nodes: 1
n_gpus: 4
n_workers: 5
node_rank: 0
embed_generator: true
embed_discriminator: true
ccgan_embedding_file: /storage/embeddings/quickdraw/embedding.pt
ccgan_embedding_dim: 128
