epochs: 300000
batch_size: 100
data_config: configs/datasets/dof.yaml
checkpoint_dir: /storage/checkpoints
experiment_name: DOF
train_config: configs/dof_training.yaml
model: models.ccgan.CCStarGAN
model_hyperparams: configs/models/dof_stargan.yaml
n_nodes: 1
n_gpus: 4
n_workers: 5
node_rank: 0
l_rec: 10
l_mse: 1
optimizer: rmsprop
discriminator_lr: -3
generator_lr_factor: 2
label_noise_variance: 0.1
