program: main.train
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - "--args_file"
  - "configs/sweeps/args/clustered_hsv.yaml"
  - "--log_hyperparams"
method: bayes
early_terminate:
  type: hyperband
  min_iter: 25
metric:
  name: rgb_l1
  goal: minimize
parameters:
  l_rec:
    distribution: uniform
    min: -1.0
    max: 1.0
  l_mse:
    distribution: uniform
    min: -1.0
    max: 1.0
  label_noise_variance:
    distribution: uniform
    min: -3
    max: -1.5
