program: main.train
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - "--args_file"
  - "configs/sweeps/args/hsv_stargan.yaml"
method: bayes
early_terminate:
  type: hyperband
  min_iter: 250
metric:
  name: val_mae
  goal: minimize
parameters:
  l_mse:
    min: 0.1
    max: 10
  l_rec:
    min: 0.1
    max: 10
  label_noise_variance:
    min: 0.001
    max: 0.05
