program: main.train
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - "--args_file"
  - "configs/sweeps/args/hue_fpgan_args.yaml"
method: bayes
early_terminate:
  type: hyperband
  min_iter: 5
metric:
  name: val_norm
  goal: minimize
parameters:
  l_mse:
    min: 0.1
    max: 10
  l_rec:
    min: 0.1
    max: 10
  l_id:
    min: 0.1
    max: 10
  l_grad_penalty:
    min: 0.1
    max: 10
