program: main.train
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - "--args_file"
  - "configs/sweeps/args/hue_ccfpgan_projection_args.yaml"
  - "--log_hyperparams"
method: bayes
early_terminate:
  type: hyperband
  min_iter: 5
metric:
  name: val_norm
  goal: minimize
parameters:
  l_rec:
    min: -1
    max: 1
  l_id:
    min: -1
    max: 1
  label_noise_variance:
    min: -3
    max: -1
