command:
  - ${env}
  - python
  - -m
  - ${program}
  - --args_file
  - configs/sweeps/args/non_cyclical_hsv.yaml
  - --log_hyperparams
early_terminate:
  min_iter: 25
  type: hyperband
method: bayes
metric:
  goal: minimize
  name: rgb_l1
parameters:
  discriminator_lr:
    values:
      - -2
      - -3
      - -4
  generator_lr_factor:
    values:
      - 1
      - 3
  l_rec:
    distribution: uniform
    max: 1
    min: -1
  l_mse:
    distribution: uniform
    max: 1
    min: -1
  optimizer:
    values:
      - rmsprop
      - adam
program: main.train
