program: main.train
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - "--args_file"
  - "configs/sweeps/args/non_cyclical_hsv.yaml"
  - "--log_hyperparams"
method: bayes
early_terminate:
  type: hyperband
  min_iter: 50
metric:
  name: val_mae
  goal: minimize
parameters:
  l_rec:
    distribution: uniform
    min: -1.0
    max: 1.0
  d_updates_per_g:
    values:
      - 1
      - 5
