program: main.train
command:
  - ${env}
  - python
  - "-m"
  - ${program}
  - "--args_file"
  - "configs/sweeps/args/quickdraw.yaml"
  - "--log_hyperparams"
method: bayes
early_terminate:
  type: hyperband
  min_iter: 25
metric:
  name: Generator.total
  goal: minimize
parameters:
  l_rec:
    distribution: uniform
    min: -1.0
    max: 1.0
  l_mse:
    distribution: uniform
    min: -1.0
    max: 1.0
  optimizer:
    values:
      - rmsprop
  discriminator_lr:
    values:
      - -2.0
      - -3.0
  generator_lr_factor:
    values:
      - 1
      - 3
  label_noise_variance:
    distribution: uniform
    min: -1
    max: 0
